### PR TITLE
fixed Warning during svelte kit build

### PR DESCRIPTION
**Pull request by bas-baskara**
I added "type":"module" into package.json to remove the warning during sveltekit build.

### CODE REVIEW

**Comment by bwklein** [comment]
@bas-baskara why did you close this?

**Comment by bas-baskara** [comment]
> @bas-baskara why did you close this?

Hi,
I closed this because I am no longer follow this package again...and now I am open it again

**Comment by bwklein** [comment]
I emailed the project owner and they are going to come in an take a look at the PRs and merge some things in.

**Comment by TahaSh** [comment]
This is fixed now in `v0.1.0`. It also supports typescript now.

Thanks, @bas-baskara and @bwklein for the PR.

**Pull request closed without merging**
